### ISSUE TITLE
BUG: No tests have been found in this workspace - for multi folder workspace

### ISSUE THREAD

**Issue by ak99372** [microsoft/playwright-vscode#108]
When the workspace includes multiple folders/projects the extension will not find the tests.

![image](https://user-images.githubusercontent.com/9924769/154862536-a21df267-56a8-4c5b-ba34-90083836be51.png)

![image](https://user-images.githubusercontent.com/9924769/154862489-721684f2-402e-4fe9-b884-84ea082a9a7b.png)

Only when the project (where tests are) is opened on it's own tests are discovered

![image](https://user-images.githubusercontent.com/9924769/154862574-bf879046-8530-4915-b65b-923ad66594cb.png)

![image](https://user-images.githubusercontent.com/9924769/154862624-ce8e75e5-feab-4b6e-b0b6-b9190e1689f6.png)

**Comment by pavelfeldman** [comment]
The fix should be live.
