### ISSUE TITLE
cannot set some env variables

### ISSUE THREAD

**Issue by SpiderZZZ** [microsoft/playwright-vscode#110]
before update to last version we have a extenstion setting "playwright.env". what about new version plugin and env variables ?

**Comment by mxschmitt** [comment]
We recommend using dotenv inside your config:  https://github.com/microsoft/create-playwright/blob/89ddb5b95eba82928371b422d22b52e9d91b48a1/assets/playwright.config.ts#L8

**Comment by cmfcmf** [comment]
I don't think this approach would work for the `PW_EXPERIMENTAL_TS_ESM` environment variable which is needed since Playwright v1.18.0 (https://github.com/microsoft/playwright/releases/tag/v1.18.0) when your `package.json` file contains `"type": "module"`. Playwright cannot read the `playwright.config.ts` file without that environment variable being present.

**Comment by SpiderZZZ** [comment]
> We recommend using dotenv inside your config: https://github.com/microsoft/create-playwright/blob/89ddb5b95eba82928371b422d22b52e9d91b48a1/assets/playwright.config.ts#L8

i neet to use some env variables to start tests on different envoriment from the extenstion, how i can do this now?
my scripts now:
```
  "scripts": {
    "test": "set NODE_ENV=test&&npx playwright test",
    "test-dev": "set NODE_ENV=dev&&npx playwright test --grep-invert @only-test",
    "debug": "set NODE_ENV=test&&npx playwright test --headed --timeout=0",
    "debug-dev": "set NODE_ENV=dev&&npx playwright test --grep-invert @only-test --headed --timeout=0"
  }
```

**Comment by loganromero** [comment]
> > We recommend using dotenv inside your config: https://github.com/microsoft/create-playwright/blob/89ddb5b95eba82928371b422d22b52e9d91b48a1/assets/playwright.config.ts#L8
> 
> i neet to use some env variables to start tests on different envoriment from the extenstion, how i can do this now? my scripts now:
> 
> ```
>   "scripts": {
>     "test": "set NODE_ENV=test&&npx playwright test",
>     "test-dev": "set NODE_ENV=dev&&npx playwright test --grep-invert @only-test",
>     "debug": "set NODE_ENV=test&&npx playwright test --headed --timeout=0",
>     "debug-dev": "set NODE_ENV=dev&&npx playwright test --grep-invert @only-test --headed --timeout=0"
>   }
> ```

This is a similar concern for me. Being able to manage multiple environments would be helpful.

**Comment by pavelfeldman** [comment]
You should create two configs:

`dev.playwright.config.ts`
and
`test.playwright.config.ts`

re-export original config from both and set necessary environment variables in each.

Then pick the one you like more in VSCode and set it as a default!

**Comment by loganromero** [comment]
Thanks for the comment, I've got that set up and working well for me now!

**Comment by SpiderZZZ** [comment]
Sorry, help me please. How i can do this?
>Then pick the one you like more in VSCode and set it as a default!

**Comment by loganromero** [comment]
Here's a link to a slack thread where I gave a breakdown of how to do this.

https://playwright.slack.com/archives/C02CE8Y0W01/p1646239459723379?thread_ts=1646235107.820819&channel=C02CE8Y0W01&message_ts=1646239459.723379
