### ISSUE TITLE
test-results folder getting deleted when I have this extension installed

### ISSUE THREAD

**Issue by AndyGleed** [microsoft/playwright-vscode#113]
I have noticed that since pw v1.19, having this extension installed (vscode on windows 10 here) causes the test-results folder to be removed. 

If the extension is not installed and the test-results folder exists, and then I install the extension, the test-results folder disappears.

If I run some tests, either from command line or by using this extension, I see the test-results folder get created and then removed as soon as the test run has finished.

If I roll back to pw v1.18.1, the test-results remain in place following a test run with or without the extension installed.

**Comment by SpiderZZZ** [comment]
same problem

**Comment by pavelfeldman** [comment]
This should be fixed in the Playwright 1.19.2, please update Playwright itself!

**Comment by AndyGleed** [comment]
@pavelfeldman Thank you.  It is now working again.
