### ISSUE TITLE
Question: Compatibility with POM

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright-vscode#119]
Wondering how the `timing` for each step and `highlighting` for each step is intended to work with POM since the actions are in different files?

Thanks!

**Comment by mxschmitt** [comment]
```txt
// #1
class MyPom() {
  foooo() {
    await page.click(); // 25ms
  }
}
// #2
test('fooo', ({myPom}) => {
  await myPom.foooo(); // # 25ms
}
```

Hey! do you mean something like shown in example 1 or example 2?

**Comment by mxschmitt** [comment]
Closing, since #1 should work. If not, please file a bug!
