### ISSUE TITLE
0.2.2 not published?

### ISSUE THREAD

**Issue by benmccann** [microsoft/playwright-vscode#123]
I see the version bumped to 0.2.2 here: https://github.com/microsoft/playwright-vscode/commit/d21292583be0fcb60c33bf07dcb63d58753189f7

But the "Version History" tab only shows up to 0.2.1: https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright#run-tests-with-a-single-click

**Comment by pavelfeldman** [comment]
At this point we release from trunk, this means that after each version is released, we bump to the next running version.

**Comment by benmccann** [comment]
Thanks for the update. In that case, I wonder if we might need to reopen https://github.com/microsoft/playwright-vscode/issues/98 as it still does not seem to be working with pnpm for me

I checked out the https://github.com/sveltejs/kit repository and it keeps telling me that I need to install playwright eventhrough it is installed (https://github.com/sveltejs/kit/blob/353d94e6f8bd57445daeeaac9d5dfc93e1068bf7/packages/kit/package.json#L18). Might I be doing something wrong?

**Comment by joeinnes** [comment]
@benmccann did you get this working eventually?

**Comment by benmccann** [comment]
No, it's not working for me. I just filed an issue: https://github.com/microsoft/playwright-vscode/issues/160
