### ISSUE TITLE
Suggest extension if not installed, and playwright config is detected

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/playwright-vscode#126]
If `workspaceContains:**/*playwright*.config.{ts,js,mjs}` AND extension not already installed, display a message to "Try Playwright extension", including the option to "never show again". An example of this can be found in the extension here: https://github.com/microsoft/vscode-azurearmtools/pull/1336/files

**Comment by pavelfeldman** [comment]
Looks like explicit anti-pattern, VSCode extensions should not advertise themselves!

**Comment by MarcusFelling** [comment]
@pavelfeldman All of our Azure extensions do this: 
![image](https://user-images.githubusercontent.com/6855361/156045364-7a3dfc9a-9457-4053-bd10-43c6570d6d30.png)

It's pretty unintrusive as it can have a "never show again" button.

**Comment by pavelfeldman** [comment]
Ah, I think I got you wrong, you were not talking about suggestion upon activation.
