### ISSUE TITLE
Test aren't starting: 'The test run did not record any output.'

### ISSUE THREAD

**Issue by baptisteArno** [microsoft/playwright-vscode#129]
https://user-images.githubusercontent.com/16015833/156052588-36e91686-3227-41fc-a50a-5ef30dd71439.mp4

**Comment by pavelfeldman** [comment]
You probably have multiple playwright config files and only one of them is enabled. See drop down next to Play action in test tree toolbar.

**Comment by baptisteArno** [comment]
Indeed! Thanks 👍

**Comment by pavelfeldman** [comment]
Closing as per above.
