### ISSUE TITLE
Can't run tests when there are multiple config files

### ISSUE THREAD

**Issue by scottfwalter** [microsoft/playwright-vscode#136]
I have this directory structure:

/e2e
  /suite01
     suite01.playwright.config.ts
  /suite03
     suite03.playwright.config.ts

I see the tests from both configs:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/1752854/156659536-cbcab770-2fcb-40c4-a244-abaa5d9591c5.png">

However, I can't run the tests from the second config, suite03.   I just see 0/0 tests passed:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/1752854/156659752-d1c5cc78-88ae-4980-96f1-3ff04fbc905f.png">

However, if I rename "suite01.playwright.config.ts" to "suite01.config.ts" so that the extension won't pickup the tests from the first suite then tests run from the second config.

It seems to have an issue with multiple suites.

**Comment by pavelfeldman** [comment]
You should enable that second config in the drop downs next to 'Play' and 'Debug' in the toolbar above.

**Comment by scottfwalter** [comment]
Ahh I think I figured it out.  I need to set all my config files to be set as default by using the Select Default Profile option:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/1752854/156892224-412d719a-eb19-47ac-8e88-887f61bf548b.png">

<img width="749" alt="image" src="https://user-images.githubusercontent.com/1752854/156892245-87153619-922f-4be5-8396-96a46cb21475.png">


@pavelfeldman Thanks for hint with the  Play and Debug toolbar items.
