### ISSUE TITLE
Extension host terminated unexpectedly when running playwright test in debug

### ISSUE THREAD

**Issue by jiimbo5** [microsoft/playwright-vscode#137]
![image](https://user-images.githubusercontent.com/99375388/156713656-f7906316-31b8-4ab9-b89e-b7aa2ec905fa.png)
Playwright version: 1.19.2
Playwright extension version: 0.2.2

When debugging a Playwright test in VS Code I am getting the following error:
![image](https://user-images.githubusercontent.com/99375388/156713691-817f2d3b-8557-4093-b564-3f42ae81f741.png)
![image](https://user-images.githubusercontent.com/99375388/156713892-e5552472-aff8-4e9f-882b-a1a41d5d4b91.png)

This is happening when this assertion fails:
![image](https://user-images.githubusercontent.com/99375388/156713779-8f9d8aa3-d7b9-461f-bb5f-291b93caf0c9.png)

Note that the timeout is exceeded but an error is not shown, instead it looks like the above screenshot until it crashes.
This is not happening 100% of the time when assertions fail. I am not sure how to verify if something in our app is causing this? Also note that there is plenty of available system memory and restarting did not fix this.

Thanks

**Comment by mxschmitt** [comment]
How much system memory do you have?

**Comment by jiimbo5** [comment]
I have 32GB and there is about 15GB available while the test runs.

**Comment by jiimbo5** [comment]
I moved to a new machine and I am not getting this error anymore. I will open another issue if I see it again.
