### ISSUE TITLE
Error when Install Playwright command is executed.

### ISSUE THREAD

**Issue by srikanthmasanala** [microsoft/playwright-vscode#139]
Error when Install Playwright command is executed from command palette
Occurs in Windows and Mac OS
<img width="975" alt="Screenshot 2022-03-05 at 6 46 06 PM" src="https://user-images.githubusercontent.com/13347346/156888596-9303acf1-de19-4a9f-b66d-33e2207ee2e8.png">

**Comment by mxschmitt** [comment]
This is fixed, closing.
