### ISSUE TITLE
[Question] VS Code Extension assumes specific project definition for browser types  

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright-vscode#151]
I see that the VS Code extension makes an assumption that the playwright.config.ts uses projects for browser types. Example : 
>   /* Configure projects for major browsers */
>   projects: [
>     {
>       name: 'chromium',
>       use: {
>         ...devices['Desktop Chrome'],
>       },
>     },
> 
>     {
>       name: 'firefox',
>       use: {
>         ...devices['Desktop Firefox'],
>       },
>     },
>     ...
> 

I have already made good use of projects to distinguish between different deployment environments such as Dev, QA, Staging, Preview, Sandbox, Production. Example:
> 
>     projects: [
>         {
>             name: 'qa',
>             use: {
>                 screenshot: 'only-on-failure',
>                 video: 'retain-on-failure',
>                 trace: 'retain-on-failure',
>                 // launchOptions: { slowMo: 500},
>                 // headless: false
>                 zdname: 'test2@gmail.com',
>                 zdbaseurl: 'https://zzzddd-qa.io/ktn2',
>                 holdbaseurl: 'https://qa.lllhhhpro.com/z/ktn2',
>                 ddpbaseurl: 'https://pppdddppp.com/#/projects?zdiscoTenant=ktn2',
>             }, // use
>         },
>         {
>             name: 'staging',
>             use: {
>                 screenshot: 'only-on-failure',
>                 video: 'retain-on-failure',
>                 trace: 'retain-on-failure',
>                 // launchOptions: { slowMo: 500},
>                 headless: false,
>                 zdname: 'test1@juno.com',
>                 zdbaseurl: 'https://zzzddd-staging.io/ktn',
>                 holdbaseurl: 'https://staging.lllhhhpro.com/z/ktn',
>                 ddpbaseurl: 'https://pppdddppp.com/#/projects?zdiscoTenant=ktn',
>             }, // use
>         },
> 

Can the two usages be unified?
If not, it appears that the VS Code integration will be confused when trying to click on test runs etc.

**Comment by pavelfeldman** [comment]
There is no such assumption baked in!

**Comment by khtan** [comment]
Apologies for a beginner's misunderstanding. You r right, and that is good.
The Test Explorer double-triangle "Select profile" looks at the values of projects to make it easier to run with a project.
The demo example uses browsertype values in the projects, and hence the options shows up as "chromium, firefox etc".
So in my deployment projects, I see options as "qa, staging, preview etc".
This ticket can be closed. 
Thanks,
