### ISSUE TITLE
Execution does not stop at the breaking point when debugging

### ISSUE THREAD

**Issue by alexkyrylenkoproven** [microsoft/playwright-vscode#157]
Hi all, I have a breakpoint on the line 5(left pane). When I click debug button, there is another windows open(right pane) that wraps my code in try/catch for some files. And for the other file, the breakpoint is not even invoked and the script runs through without stopping at the breakpoint. I used to have the debugger works normally but now I get this second file. 
![image](https://user-images.githubusercontent.com/99697912/165355891-0ff17d47-eef6-47bc-9828-368fa7bdc9c0.png)

**Comment by pavelfeldman** [comment]
What you see on the left is source code. What you see on the right is the transpiled code that actually executed. VS Code is supposed to recognize this source mapping url on line 35 and hide the transpiled code. For some reason this does not happen. Could this be that you disabled sources maps in VS Code using some setting?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
