### ISSUE TITLE
Install : The term 'Install' is not recognized as the name of a cmdlet, function, script file, or operable 

### ISSUE THREAD

**Issue by nssidhu** [microsoft/playwright-vscode#164]
I am following you "Get Started Document" from 
https://playwright.dev/docs/intro#installation

I Installed the Visual Studio extension and the next thing i tried is this, but got the following error

```
PS C:\Users\nssid> Install Playwright
Install : The term 'Install' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try  
again.
At line:1 char:1
+ Install Playwright
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by mxschmitt** [comment]
The vscode extension is only compatible with the Node.js version of Playwright.

See here for the .NET getting started: https://playwright.dev/dotnet/docs/intro#installation

**Comment by nssidhu** [comment]
Sorry for the typo there, I installed visual studio code extension. 
I don't want to use .NET, but instead of node.js

The article above which i am trying to follow is for Node.js

**Comment by mxschmitt** [comment]
It's a command which you need to invoke with the vscode command palette, not the terminal.

See here: https://code.visualstudio.com/docs/getstarted/userinterface#:~:text=Command%20Palette%23,for%20the%20most%20common%20operations.

**Comment by nssidhu** [comment]
> It's a command which you need to invoke with the vscode command palette, not the terminal.
> 
> See here: https://code.visualstudio.com/docs/getstarted/userinterface#:~:text=Command%20Palette%23,for%20the%20most%20common%20operations.

@mxschmitt, Thanks that helped
