### ISSUE TITLE
HTML Report open option is ignored when running tests from extension

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright-vscode#167]
Even if in `playwright.config.ts` html report open option is set to `always`
```
reporter: [['html', { open: 'always' }]],
```
the report is not opened after test is finished. It only suggests to open report via command line.

```
Running 1 test using 1 worker

  1 passed (10s)

To open last HTML report run:

  npx playwright show-report



> Test run finished at 01/06/2022, 17:31:28 <
```

Is it a bug? Or is there some reason why the extension cannot run command to open the report?

**Comment by mxschmitt** [comment]
This is expected as of today, I'll merge it with https://github.com/microsoft/playwright-vscode/issues/175.
