### ISSUE TITLE
[Question] Is it possible to print the test results in the terminal?

### ISSUE THREAD

**Issue by elaichenkov** [microsoft/playwright-vscode#17]
First of all, I'd like to thank you for the brilliant plugin

Now the output of the test results in the terminal is just simple text of `Running` and `Completed` spec files.

But, as a user, I'd like to see the test results in the terminal in the selected reporter style (e.g `dot or list` ), which I selected in the configuration file.

Actual:

![image](https://user-images.githubusercontent.com/29764053/129883327-2d1eef20-9b23-42b4-99bb-57c12f038411.png)

Expected:

![image](https://user-images.githubusercontent.com/29764053/129883423-c8c000b9-83b8-41e4-9209-5ccecca7fc35.png)

**Comment by mxschmitt** [comment]
To have the exact same output as you've shown is expected, because it's coming from the Playwright Test reporter. But yeah we can make the current Test output more readable so it looks like the Playwright Test output, this sounds like a good idea.
