### ISSUE TITLE
trouble to start tests with example project

### ISSUE THREAD

**Issue by SpiderZZZ** [microsoft/playwright-vscode#20]
When try to start tests in example project i have this picture:

![image](https://user-images.githubusercontent.com/18137237/130011237-29ffe902-54bc-492a-8e4b-c6652725a4c7.png)

In Debug mode i have error:

![image](https://user-images.githubusercontent.com/18137237/130011502-9a1ae7d0-52fc-4794-86f7-24ff7d7728d1.png)

In output i have this:

![image](https://user-images.githubusercontent.com/18137237/130011323-71a73781-34f5-4c98-bf94-da1b1607f408.png)

Playwirhght Test For VSCode v0.0.2

VSCode
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by mxschmitt** [comment]
Hi, thanks for trying out the extension! Could you send me the output of the debug logs? You can get them as shown in the screenshot:

![image](https://user-images.githubusercontent.com/17984549/130084083-1f25a269-6b49-4272-b7f2-8df63b19d6fa.png)

Thank you.

**Comment by erwin-faceit** [comment]
I have the exact same issue, and the output tab is empty, the debug console shows the same as in issue #21. 

Run works fine, debug gives this notification. Perhaps it's possible that these two items are related?

**Comment by erwin-faceit** [comment]
Sorry, I was wrong...I didn't filter the output tab to Playwright tests. It only shows

```
2021-08-19T14:37:42.696Z Running test <name of the test> debug=true 
```

**Comment by SpiderZZZ** [comment]
> Hi, thanks for trying out the extension! Could you send me the output of the debug logs? You can get them as shown in the screenshot:
> 
> ![image](https://user-images.githubusercontent.com/17984549/130084083-1f25a269-6b49-4272-b7f2-8df63b19d6fa.png)
> 
> Thank you.

Hello!
```
2021-08-20T04:58:54.769Z Running test you [Chromium] debug=false 
2021-08-20T04:58:54.769Z Executing command: node_modules\@playwright\test\lib\cli\cli.js test --project=Chromium --reporter=json c:\Projects\playwright-vscode\example\folder-1\example1.spec.ts:39 
2021-08-20T04:58:56.864Z could not parse JSON  =================
 no tests found.
=================

2021-08-20T04:58:56.865Z Could not run tests SyntaxError: Unexpected end of JSON input
```

**Comment by mxschmitt** [comment]
Hi @SpiderZZZ we just released version 0.0.3 with the fix from @erwin-faceit so it might fix the issue in your scenario. 

Which Node.js version do you have installed on your system? (`node --version`)

**Comment by SpiderZZZ** [comment]
> Hi @SpiderZZZ we just released version 0.0.3 with the fix from @erwin-faceit so it might fix the issue in your scenario.
> 
> Which Node.js version do you have installed on your system? (`node --version`)

Hello!
It's work for me now, after update:
![image](https://user-images.githubusercontent.com/18137237/130455078-bc9d2fb9-672d-458d-86ba-781847d79897.png)

But in debug mode i still have popup:
![image](https://user-images.githubusercontent.com/18137237/130458985-74e0a805-14db-49bf-86ac-2fee5bee2e9e.png)

node --version
v14.17.3

**Comment by mxschmitt** [comment]
Maybe its related to https://github.com/microsoft/vscode/issues/74197

**Comment by SpiderZZZ** [comment]
May be this is problem ?
![image](https://user-images.githubusercontent.com/18137237/130788419-e4d46389-6e8c-470d-a2cd-923b3eb2d6bd.png)

**Comment by mxschmitt** [comment]
This looks expected. I guess your Node.js installation is broken or not correctly configured in the PATH, does normal JavaScript debugging work for you via the Visual Studio Code?

**Comment by SpiderZZZ** [comment]
fixed by reinstall extension to last version, ty!
