### ISSUE TITLE
Enable Playwright Debug take a lot of space/is distracting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright-vscode#26]
Not sure this warrants its own status bar entry? I know you can hide this easily but most users don't do this so a large portion of the status bar is taken up by this entry.

![image](https://user-images.githubusercontent.com/2193314/130456561-64222748-1f41-4bdf-8f37-d56bf8269086.png)

**Comment by mxschmitt** [comment]
Closing since in the new version which gets released soon it's not there anymore.
