### ISSUE TITLE
Detect Playwright configs in subfolders out of the box

### ISSUE THREAD

**Issue by mskelton** [microsoft/playwright-vscode#28]
Many of the projects I work on have Playwright tests in a dedicated subdirectory (e.g. `e2e`) separate from the main project which might be in `app` or `src`.  The extension by default only looks for a `playwright.config.ts` file in the root so this requires that I set `e2e/playwright.config.ts` in my settings to make the tests discoverable.

This issue could of course also apply for monorepos with multiple test projects, but this is probably a first step towards that if others have a use case for multiple Playwright projects in a single repo.

**Comment by pavelfeldman** [comment]
I think this one is fixed in 0.1.0.
