### ISSUE TITLE
Add Playwright Test version validation

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-vscode#30]
Requirements:

- VSCode 1.59+ (enforced via the extension manifest)
- Playwright Test 1.14.0+ (~~to be confirmed~~ - we should add verification)
- Operating system (mac/Windows/Linux) should all work and is tested
- Test-file names for activation: using the `*.spec.{js,ts}`, `*.test.{js,ts}` naming, we might should make this more flexible?

**Comment by mskelton** [comment]
> mac/Windows/macOS

I'm guessing you mean Linux/Windows/macOS 🙂
