### ISSUE TITLE
Add color to error output

### ISSUE THREAD

**Issue by mskelton** [microsoft/playwright-vscode#52]
Not sure if this is a VS Code issue or an issue with this extension, but having colors in the error output would be nice.

Current test results:

<img width="832" alt="Screen Shot 2021-09-07 at 9 12 26 AM" src="https://user-images.githubusercontent.com/25914066/132359721-1f42f525-bccb-4d24-8ae2-f47d3d8888f8.png">

While the CLI produces a nicer output:

<img width="981" alt="Screen Shot 2021-09-07 at 9 13 41 AM" src="https://user-images.githubusercontent.com/25914066/132359878-e9dc5353-c282-42af-8e53-9ebbd0df6aec.png">

**Comment by mxschmitt** [comment]
In the new version which gets released in 1-2 weeks this should be fixed.
