### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright-vscode#56]
You're using GH releases right now but the way to get the changelog integrated into VS Code and the marketplace is by adding a `CHANGELOG.md` file to the root of the extension folder.

**Comment by mxschmitt** [comment]
Hmm so the best would be to mirror/reflect it also in the `CHANGELOG.md`?

**Comment by mskelton** [comment]
@mxschmitt There are GitHub actions that exist that will copy notes from changelogs to a release when you push a tag.  I've used [this one](https://github.com/Roang-zero1/github-create-release-action) in the past and I actually [wrote an article](https://mskelton.medium.com/automated-npm-publishing-using-github-actions-594ef1aaabe2) about it.

Alternatively, if you use a tool like [Changesets](https://github.com/atlassian/changesets) for managing releases it will take care of putting notes in both places.

**Comment by pavelfeldman** [comment]
Triaging issues that are not in the immediate plans.

**Comment by Tyriar** [comment]
That's a shame, this makes it much harder for users to find what has changed in product.
