### ISSUE TITLE
debugging doesn't work

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright-vscode#59]
when attempting to debug, it just outputs this to the debug console and does nothing:

![image](https://user-images.githubusercontent.com/57028336/134114993-a1a4e2ee-d986-438e-acda-0de2bd5053fd.png)
![image](https://user-images.githubusercontent.com/57028336/134114227-2477fcb2-7c6f-4ea5-98d0-d7c97be12d75.png)

### main.spec.ts
```ts
import { expect, test } from '@playwright/test'

test('basic test', async ({ page }) => {
    await page.goto('https://google.com/')
    const title = page.locator('.navbar__inner .navbar__title')
    await expect(title).toHaveText('Playwright')
})
```
### playwright.config.ts
```ts
import { PlaywrightTestConfig } from '@playwright/test'

const config: PlaywrightTestConfig = {
    projects: [
        {
            name: 'Chrome Stable',
            use: {
                browserName: 'chromium',
                // Test against Chrome Stable channel.
                channel: 'chrome',
            },
        },
    ],
}
export default config
```

### playwright test output
```
2021-09-21T05:07:05.236Z Executing command: node_modules\@playwright\test\lib\cli\cli.js test --retries=0 --reporter=json --list \. 
2021-09-21T05:07:10.458Z Creating test controller: Playwright TestChrome Stable 
2021-09-21T05:07:10.459Z Executing command: node_modules\@playwright\test\lib\cli\cli.js test --retries=0 --project=Chrome Stable --reporter=json --list c:\\Users\\user\\playwright-demo\\tests\\main\.spec\.ts 
2021-09-21T05:07:12.926Z TestFile._updateFromDisk default and Chrome Stable 
2021-09-21T05:07:23.871Z Running test basic test [Chrome Stable] debug=true 
```

**Comment by mxschmitt** [comment]
When debugging a test, you need to set a break point or use the [`debugger;` statement](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/debugger). Then the debugger will pause.

Besides that I fixed an issue with projects which contains spaces that were not working, which I've released a few minutes ago to the marketplace.

**Comment by DetachHead** [comment]
@mxschmitt sorry it wasn't very visible in the screenshots but i did have breakpoints set. it didn't seem to be running the tests at all

also, my project name didn't have a space. the full path was `c:/users/myusername/playwright-demo`

**Comment by mxschmitt** [comment]
With project name I meant in your config, there is `name: 'Chrome Stable',` which has a space. Could you try using the latest version 0.0.7 which got published?

**Comment by joelhellman** [comment]
I have the exact inputs and outputs and results as DetachHead. I have no spaces in paths, tried breakpoints and debugger statement but nothing else happens when I invoke Debug Test as described in OP. 

Debug console output:
```
c:\dev\my-livetests\node_modules\@playwright\test\lib\cli\cli.js test --retries=0 --config playwright.config.js --project DesktopChromium --reporter=list c:\\dev\\my-livetests\\tests\\myfile\.spec\.js:16
```

Playwright Test output:
```
2021-10-03T00:16:25.675Z Running test <my test name> [DesktopChromium] debug=true
```

I can invoke Run Test from the same context menu and the test runs fine, with the following Playwright Test output:
```
2021-10-03T00:19:29.366Z Running test <my test name> [DesktopChromium] debug=false 
2021-10-03T00:19:29.366Z Executing command: node_modules\@playwright\test\lib\cli\cli.js test --retries=0 --config playwright.config.js --project DesktopChromium --reporter=json c:\\dev\\my-livetests\\tests\\usermate\.spec\.js:16 
```
So one difference is I don't get that line Executing command..., when I invoke the Debug Test command.

This is at v.0.0.7 on Microsoft Windows 10 Enterprise 2009 (10.0.19043).

**Comment by KaterynaPodobraya** [comment]
I have 2 different projects with playwright tests.
One of them I am running on a Windows 10 , the second one I am running on Linux Mint 20.2. 
Plugin version is 0.0.9 for both projects. 
Debug works on Linux Mint ONLY.  
On Windows have the same behavior as described by @devzerker , @DetachHead, @joelhellman .

**Comment by SpiderZZZ** [comment]
same problem in windows

**Comment by mxschmitt** [comment]
In the new version which gets released in 1-2 weeks we reworked this fully. This is then working as expected.

**Comment by DetachHead** [comment]
@mxschmitt i've just tested this on the new version and still have the same problem. can this issue please be re-opened?

let me know if there's any additional information you need

**Comment by DetachHead** [comment]
seems to be fixed now, thanks!

**Comment by mxschmitt** [comment]
@DetachHead thanks for all your feedback!
