### ISSUE TITLE
Split tests in the tree based on their folder structure

### ISSUE THREAD

**Issue by jespertheend** [microsoft/playwright-vscode#70]
At the moment all test files are shown as a list in the root of the tree, but this results in many similar entries if you have a bunch of files in the same folder.
I think it would make much more sense if the tests were structured by their folder structure. That way it would be much easier to find a specific test, and it would be very easy to run all tests in a specific folder.
I believe this how the jest vscode extension handles it as well.

**Comment by mxschmitt** [comment]
We release a new version in 1-2 weeks. This is then fixed!
