### ISSUE TITLE
Playwright Test for VSCode only reads environment variables on installation

### ISSUE THREAD

**Issue by Ghislain89** [microsoft/playwright-vscode#72]
Steps to reproduce:

- Install Playwright for VSCode
- Add environment variables
`"playwright.env": {
        "baseUrl": "<url here>",
        "proxyUser": "<username here>",
        "proxyPass": "password here"
    },`

expected result:
Playwright for VsCode will use the environment variables in the following test processes

Observed result:
Playwright for VsCode does not use the environment variables in the following test processes.

It seems Playwright for VsCode only loads the environment variables when you install the extension. If you have the extension and you change a variable, you'll have to reinstall the extension in order to get it picked up.

**Comment by mxschmitt** [comment]
We recommend dotenv for that. You can put `require('dotenv').config()` inside your config and then it will read your .env files.
