### ISSUE TITLE
[Bug] v2 doesn't discover tests in nested folders

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/playwright-vscode#80]
Extension activates, but it doesn't discover any tests. My workspace with dir one level deep (tests/test.spec.ts) works, my workspace with dir 2 levels deep does not (ToDoMVC/tests/test.spec.ts)

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright-vscode/blob/main/tests/file-tree.spec.ts#L67 - this passes on Windows. I think this is due to the local modifications we applied that disabled filters.

**Comment by MarcusFelling** [comment]
No, this was in separate workspace outside of VS Code repo.
