### ISSUE TITLE
Extension does not appear in the UI

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright-vscode#87]
Extension version: v0.0.9
Playwright version: 1.18.0
VS Code: 1.63.2

One package.json in the root. Tests are in root/tests folder named with pattern of `*.ts`
The extension does not appear in the UI. Is there any way to solve this? 

![Screenshot at Feb 09 12-09-38](https://user-images.githubusercontent.com/17873445/153176759-84943eec-0423-4e8e-818c-5410f5c5f3d8.png)

**Comment by mxschmitt** [comment]
Hey! We are currently in the process of rewriting the extension and it should get released in a few weeks. In the meantime you can test the development builds here which should have a lot of bugfixes including this one: https://github.com/microsoft/playwright-vscode/wiki/Installation
