### ISSUE TITLE
Monorepo unable to discover playwright tests

### ISSUE THREAD

**Issue by murugaratham** [microsoft/playwright-vscode#93]
I have a monorepo with .net core backend, react spa
```
├── backend
│   ├── ...
├── frontend
│   ├── e2e
│   │   ├── tests
|   |   |    ├── test.spec.ts
|   |   |    ├── ..
|   |   ├──..
│   │   ├── ..
│   ├── ..
└── .gitignore
```
`2022-02-16T02:53:23.200Z Error: Could not locate Playwright Test. Is it installed? 'npm install -D @playwright/test' 
`

I open workspace @ containing folder of backend & frontend, when i use test explorer, i can only see my backend tests

**Comment by mxschmitt** [comment]
Are you using the preview version? (Inside vs code, search for the extension, click on it, click on use preview version)
Are you using playwright 1.19?
It currently only works with a playwright.config.

**Comment by murugaratham** [comment]
Yes i'm on pre-release v0.1.0, where can i see the documents to hint playwright for discoverability?

**Comment by mxschmitt** [comment]
There is none, but if you use e.g. the config which `npm init playwright` gives you, it should work: https://github.com/microsoft/create-playwright/blob/main/assets/playwright.config.ts

We're also considering supporting the use without a config, so I can consider this issue as a feature request.

**Comment by pavelfeldman** [comment]
You need to have a config for extension to work!

**Comment by UndefinedOffset** [comment]
I was running into this as well for me it appears to be similar to #77, the `playwright-core` package ends up under `node_modules/@playwright/test/node_modules/playwright-core`. Now if I require playwright-core in my application it does put it in the root of `node_modules` where this extension seems to be expecting it to be but it also ends up in that location.

Once that's done however it does seem to properly pick up the tests. They don't run (`electron.launch: Process failed to launch`) but that's for another issue.

NodeJS: v14.18.3
NPM: 6.14.16
Playwright: 1.19.1
Playwright/Test: 1.19.1
OS: Windows 10 21H1

**Comment by pavelfeldman** [comment]
@UndefinedOffset thanks for the report! Any idea why it puts playwright-core to under @playwright/test? Do you have a conflicting playwright-core among your dependencies?

**Comment by UndefinedOffset** [comment]
Shouldn't be here's my package.json

```
{
  "name": "package-name",
  "productName": "Product Name",
  "version": "4.8.0",
  "description": "Application Description",
  "main": "src/main-process/main.js",
  "scripts": {
    "start": "electron .",
    "lint": "eslint",
    "lint:report": "eslint --output-file eslint_report.json --format json",
    "test": "playwright test"
  },
  "repository": "https://github.com/org-name/repo-name",
  "keywords": [],
  "author": "Author Name",
  "license": "BSD-3-Clause",
  "devDependencies": {
    "@babel/cli": "^7.17.3",
    "@babel/core": "^7.17.4",
    "@babel/plugin-transform-react-jsx": "^7.17.3",
    "@playwright/test": "^1.19.1",
    "@sentry/cli": "^1.72.2",
    "adm-zip": "^0.5.9",
    "axios": "^0.26.0",
    "babel-plugin-root-import": "^6.6.0",
    "css-loader": "^6.6.0",
    "dotenv": "^16.0.0",
    "electron": "^17.0.1",
    "electron-packager": "^15.4.0",
    "electron-process-reporter": "^1.4.0",
    "electron-winstaller": "^5.0.0",
    "eslint": "^8.9.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-import-resolver-babel-plugin-root-import": "^1.1.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsdoc": "^37.9.1",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "file-loader": "^6.2.0",
    "mini-css-extract-plugin": "^2.5.3",
    "object-path": "^0.11.8",
    "playwright": "^1.19.1",
    "resolve-url-loader": "^5.0.0",
    "sass": "^1.49.7",
    "sass-loader": "^12.6.0",
    "url-loader": "^4.1.1",
    "webpack": "^5.69.0",
    "webpack-cli": "^4.9.2"
  },
  "dependencies": {
    "@electron/fuses": "^1.5.0",
    "@fortawesome/fontawesome-pro": "^6.0.0",
    "@sentry/electron": "^3.0.0",
    "electron-settings": "^4.0.2",
    "etch": "^0.14.1",
    "uuid": "^8.3.2"
  },
  "babel": {
    "plugins": [
      "@babel/transform-react-jsx",
      [
        "babel-plugin-root-import",
        {
          "paths": [
            {
              "root": "./src",
              "rootPathSuffix": "src",
              "rootPathPrefix": "~/"
            }
          ]
        }
      ]
    ]
  }
}

```

**Comment by pavelfeldman** [comment]
I'm also seeing "playwright": "^1.19.1", in the list, it also depends on playwright-core, should depend on the same version. Does it also have its own copy? I.e. did you end up with two identical `playwright-core`s under playwright/node_modules and @playwright-test/node_modules? Btw, you typically don't need `playwright` module unless you are using Playwright as a library.

**Comment by pavelfeldman** [comment]
(I'm pretty sure npm v7 and npm v8 will solve your problem)
