### ISSUE TITLE
cancelling the recorder should delete the generated spec file as well

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright-vscode#96]
when you hit F1 and run the "Record Playwright Test" task, it creates this file:
![image](https://user-images.githubusercontent.com/57028336/154370621-94766e68-98f2-4fe1-959c-dd2bd2996b45.png)

when you click this "Cancel" button, it doesn't save any recorded steps, so it should automatically delete the file
![image](https://user-images.githubusercontent.com/57028336/154370926-68afd4bf-2a00-4f8d-b585-7647f57a3c70.png)

**Comment by pavelfeldman** [comment]
If we do as you are suggesting, it'll be unclear whether the file should be deleted when user cancels the recording that already has some steps. We prefer to be on the safe side and keep the file at all times!

**Comment by DetachHead** [comment]
when the recording already has steps and you hit cancel, they don't get saved to the file anyway. i suppose the user could edit the file while they're recording but those edits get overwritten either way
