### ISSUE TITLE
Does not work with pnpm workspace

### ISSUE THREAD

**Issue by kuechlerm** [microsoft/playwright-vscode#98]
I have a root pnpm workspace that includes a folder ./e2e-tests with a default Playwright setup.
The test runner says : "No tests have been found in this workspace yet."
I tried to set dotnet-test-explorer.testProjectPath with no luck.

Using pnpm in a non-workspace setup works fine,

All Playwrite setups are done with the default `npm init playwright new-project` command.

Any ideas how to fix that?

**Comment by pavelfeldman** [comment]
Could you provide exact steps so that I could folow?

**Comment by kuechlerm** [comment]
You can clone this and run pnpm in the root folder:
https://github.com/kuechlerm/vs-code-playwright-problem

**Comment by mxschmitt** [comment]
Thank you!

I was able to reproduce it. It's fixed by https://github.com/microsoft/playwright-vscode/pull/99 and we'll release a new version with the fix shortly.

**Comment by kuechlerm** [comment]
Thank you! And thanks for the extension.
